package com.epam.finalproject.comand.constant;

public class AttributeName {

    public final static String ERROR_LOGIN_ALREADY_EXISTS = "errorLoginAlreadyExists";
    public final static String ERROR_LOGIN_OR_PASSWORD = "errorLoginPassMessage";
    public final static String ERROR_LOGIN = "errorLogin";
    public final static String ERROR_PASSWORD = "errorPassword";
    public final static String ERROR_REPEAT_PASSWORD = "errorRepeatPassword";
    public final static String ERROR_FIRST_NAME = "errorFirstName";
    public final static String ERROR_LAST_NAME = "errorLastName";
    public final static String ERROR_MAIL = "errorEmail";
    public final static String WRONG_ACTION = "wrongAction";
    public final static String NULL_PAGE = "nullPage";
    public final static String LOGIN = "login";
    public final static String USERS = "users";
    public final static String USERS_WITH_PERSONAL_TRAINER = "usersWithPersonalTrainer";
    public final static String USERS_WITHOUT_EXERCISES = "usersWithoutExercises";
    public final static String USERS_WITHOUT_DIET = "usersWithoutDiet";
    public final static String USER = "user";
    public final static String USER_ID = "userId";
    public final static String LOCAL = "local";
    public final static String ROLE = "role";
    public final static String FIRST_NAME = "firstName";
    public final static String LAST_NAME = "lastName";
    public final static String MAIL = "mail";
    public final static String TRAINERS = "trainers";
    public final static String REDIRECT = "redirect";
    public final static String CURRENT_USER_ID = "currentUserId";
    public final static String CURRENT_USER_LOGIN = "currentUserLogin";
    public final static String ALL_EXERCISES = "AllExercises";
    public final static String ALL_DIETS = "AllDiets";
    public final static String ALL_PERSONAL_DIETS = "allPersonalDiets";
    public final static String ALL_NOT_SAME_EXERCISES = "allNotSameExercises";
    public final static String EXERCISES = "exercises";
    public final static String USER_COMMENT = "userComment";
    public final static String DIET = "diet";
    public final static String USER_DIET = "userDiet";
    public final static String STATUS = "status";
    public final static String USER_STATE = "userState";
    public final static String COMMENTS = "comments";
    public final static String NOT_ACTIVE_ACCOUNT = "notActiveAccount";
    public final static String ALL_DELETED_USERS = "allDeletedUsers";
    public final static String USER_EXERCISES = "userExercises";
    public final static String DISCOUNT = "discount";
    public final static String ERROR_USER_ALREADY_PAID = "userAlreadyPaid";
    public final static String PRICE_WITH_DISCOUNT = "priceWithDiscount";
    public final static String NUMBER_OF_VISITS = "numberOfVisits";
    public final static String PERSONAL_TRAINER = "personalTrainer";
    public final static String ERROR_CARD_DATA = "errorCardData";
    public final static String ERROR_PAYMENT = "errorPayment";
    public final static String CURRENT_TRAINER_USERS = "currentTrainerUsers";
    public final static String PERSONAL_USERS_FOR_MARK = "personalUsersForMark";
}